version: '3.5'
networks:
  catalogue_net:
volumes:
    postgres-data:
services:
  db:
    image: postgres:10.5
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    networks:
        - catalogue_net
    ports: 
        - '5435:5432'
    volumes:
        - postgres-data:/var/lib/postgresql/data
  api:
    build: 
        context: ./
    depends_on:
        - db
    networks:
        - catalogue_net
    ports:
        - ${API_PORT}:${API_PORT}
    environment:
        - API_PORT=${API_PORT}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    volumes:
        - ./api:/catalogue/api
    command: ["./main", "-serve"]    
        
